### ISSUE TITLE
Android 8.0无法收到消息

### ISSUE THREAD

**Issue by woshidag** [yunba/yunba-java-sdk#6]
你好，我在android things （android 8.0）下使用yunba
出现下面的信息：
01-01 02:20:17.710 296-311/system_process W/BroadcastQueue: Background execution not allowed: receiving Intent { act=io.yunba.android.MESSAGE_RECEIVED_ACTION cat=[com.aoxun.thingstest] flg=0x10 (has extras) } to com.aoxun.thingstest/.receiver.YunbaReceiver

**Comment by LongMiao** [comment]
@woshidag 根据 [后台执行限制](https://developer.android.com/about/versions/oreo/background.html?) 里面所说，Android O 限制了隐式广播从而会导致应用层接受消息失败。但有存在两种情况依然能收到隐式广播：

1. App `targetSdkVersion` <= 25

2. 使用 `registerRecevier()` 动态注册广播接收器

请尝试在以上两种情况下测试看是否会出现类似的问题，我们的 Android Sdk 也会针对此问题进行支持

**Comment by woshidag** [comment]
感谢 使用第一种方法即可正常收到消息
